java -jar compiler.jar \
    --js ./rushmore/app/app.js \
    --js ./rushmore/app/components/config.js \
    --js ./rushmore/app/views/playerCreation/playerCreation.js \
    --js ./rushmore/app/views/game/game.js \
    --js ./rushmore/app/views/game/joystick.js \
    --js ./rushmore/app/views/gameJoin/gameJoin.js \
    --js ./rushmore/app/views/lobby/lobby.js \
    --js ./rushmore/app/views/tutorials/tutorial.js \
    --js ./rushmore/app/views/stats/stats.js \
    --js ./rushmore/app/views/headerBarInfo.js \
    --js ./rushmore/app/components/services/socketFactory.js \
    --js ./rushmore/app/components/services/NetworkService.js \
    --js ./rushmore/app/components/services/StorageService.js \
    --js ./rushmore/app/components/services/GameInfoService.js \
    --js ./rushmore/app/components/services/SpecialPowerManagerService.js \
    --js ./rushmore/app/components/services/ColorService.js \
    --js ./rushmore/app/components/services/InputHandlerService.js \
    --js ./rushmore/app/components/services/LocationService.js \
    --js ./rushmore/app/components/services/UserService.js \
    --js ./rushmore/app/components/services/TutorialService.js \
    --js ./rushmore/app/components/services/ClassService.js \
    --js ./rushmore/app/bower_components/angular-toastr/dist/angular-toastr.tpls.js \
    --js ./rushmore/app/bower_components/ng-idle/angular-idle.js \
    --js ./rushmore/app/bower_components/angular-local-storage/dist/angular-local-storage.js \
    --js ./rushmore/app/bower_components/angular-socket-io/socket.js \
    --js ./rushmore/app/bower_components/angular-route/angular-route.js \
    --js_output_file ./rushmore/app/resources/js/rushmore.js